global:
  scrape_interval: 15s # How frequently to scrape metrics
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'authentication-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['authentication-ms:8080']
        labels:
          application: 'authentication-ms'

  - job_name: 'appointment-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['appointment-ms:8081']
        labels:
          application: 'appointment-ms'