global:
  scrape_interval: 15s # How frequently to scrape metrics
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'authentication-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # If running Prometheus in Docker locally, use host.docker.internal to reach the host machine.
      # If running natively, use localhost:8080.
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'authentication-ms'
          environment: $SPRING_PROFILE