spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/miro_appointment_db
    username: erik.g
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

app:
  jwt:
    secret: ${APP_JWT_SECRET} # Shared with auth-ms