spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/miro_auth_db}
    username: ${DB_USERNAME:macbook}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000 # 1 hour

logging:
  level:
#    org.flywaydb: DEBUG # See flyway working logs
    org.hibernate.orm.jdbc.bind: trace
