spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/miro_auth_db
    username: erik.g
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: supersecretkeythatisverylongandsecureforjwtsigning123!
    expiration-ms: 3600000 # 1 hour
